import { useAnalytics } from '../hooks/useAnalytics';
import Card from '../components/ui/Card';
import { PageLoader } from '../components/ui/Spinner';
import PageHeader from '../components/layout/PageHeader';
import LineChart from '../components/charts/LineChart';
import BarChart from '../components/charts/BarChart';
import FunnelChart from '../components/charts/FunnelChart';
// utils used inline below
import { useMemo } from 'react';
import type { DailyReport } from '../lib/api';
import { Download } from 'lucide-react';
import Button from '../components/ui/Button';
import { downloadReport } from '../lib/api';
import { downloadBlob } from '../lib/utils';
import toast from 'react-hot-toast';

/**
 * The Analytics page visualizes historical performance data.
 * 
 * It aggregates daily reports generated by the backend and displays them using
 * various charts (Funnel, Line, Bar) to help users understand conversion rates,
 * discovery volume, and outreach efficacy over time. Users can also download 
 * raw report data as JSON.
 */
export default function Analytics() {
  const { data: reports, isLoading } = useAnalytics();

  const chartData = useMemo(() => {
    if (!reports?.length) return { line: [], bar: [], funnel: [] };

    const sortedReports = [...reports].sort((a, b) =>
      new Date(a.report_date).getTime() - new Date(b.report_date).getTime()
    );

    const line = sortedReports.map((r: DailyReport) => ({
      date: r.report_date,
      leads_discovered: r.leads_discovered ?? 0,
      emails_sent: r.emails_sent ?? 0,
      emails_opened: r.emails_opened ?? 0,
    }));

    const bar = sortedReports.map((r: DailyReport) => ({
      date: r.report_date,
      qualified: r.leads_qualified ?? 0,
      sent: r.emails_sent ?? 0,
    }));

    // Funnel: aggregate from last 7 reports
    const recent = sortedReports.slice(-7);
    const totals = recent.reduce(
      (acc, r) => ({
        discovered: acc.discovered + (r.leads_discovered ?? 0),
        qualified: acc.qualified + (r.leads_qualified ?? 0),
        personalized: acc.personalized + (r.emails_personalized ?? 0),
        emailed: acc.emailed + (r.emails_sent ?? 0),
        opened: acc.opened + (r.emails_opened ?? 0),
      }),
      { discovered: 0, qualified: 0, personalized: 0, emailed: 0, opened: 0 },
    );

    const funnel = [
      { label: 'Discovered', value: totals.discovered, color: '#111111' },
      { label: 'Qualified', value: totals.qualified, color: '#333333' },
      { label: 'Personalized', value: totals.personalized, color: '#666666' },
      { label: 'Emailed', value: totals.emailed, color: '#999999' },
      { label: 'Opened', value: totals.opened, color: '#A4DBD9' },
    ];

    return { line, bar, funnel };
  }, [reports]);

  const handleDownloadReport = async (date: string) => {
    try {
      const blob = await downloadReport(date);
      downloadBlob(blob, `report_${date}.json`);
      toast.success('Report downloaded');
    } catch {
      toast.error('Download failed');
    }
  };

  if (isLoading) return <PageLoader />;

  return (
    <div className="space-y-6 animate-fade-in">
      <PageHeader
        title="Analytics"
        subtitle={`${reports?.length ?? 0} daily reports`}
      />

      {/* Funnel */}
      <Card>
        <h3 className="text-xs font-medium text-gray-500 uppercase tracking-widest mb-4">Lead Funnel (Last 7 Days)</h3>
        <FunnelChart stages={chartData.funnel} />
      </Card>

      {/* Charts Row */}
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
        <Card>
          <h3 className="text-xs font-medium text-gray-500 uppercase tracking-widest mb-4">Lead Discovery & Emails</h3>
          <LineChart
            data={chartData.line}
            lines={[
              { dataKey: 'leads_discovered', color: '#111111', label: 'Leads' },
              { dataKey: 'emails_sent', color: '#666666', label: 'Emails Sent' },
              { dataKey: 'emails_opened', color: '#A4DBD9', label: 'Emails Opened' },
            ]}
          />
        </Card>

        <Card>
          <h3 className="text-xs font-medium text-gray-500 uppercase tracking-widest mb-4">Qualification & Outreach</h3>
          <BarChart
            data={chartData.bar}
            bars={[
              { dataKey: 'qualified', color: '#111111', label: 'Qualified' },
              { dataKey: 'sent', color: '#A4DBD9', label: 'Sent' },
            ]}
          />
        </Card>
      </div>

      {/* Reports Table */}
      <Card>
        <h3 className="text-xs font-medium text-gray-500 uppercase tracking-widest mb-4">Daily Reports</h3>
        <div className="overflow-x-auto">
          <table className="w-full text-sm">
            <thead>
              <tr className="border-b border-gray-200">
                <th className="px-4 py-3 text-left text-xs font-medium uppercase tracking-widest text-gray-400">Date</th>
                <th className="px-4 py-3 text-left text-xs font-medium uppercase tracking-widest text-gray-400">Discovered</th>
                <th className="px-4 py-3 text-left text-xs font-medium uppercase tracking-widest text-gray-400">Qualified</th>
                <th className="px-4 py-3 text-left text-xs font-medium uppercase tracking-widest text-gray-400">Sent</th>
                <th className="px-4 py-3 text-left text-xs font-medium uppercase tracking-widest text-gray-400">Opened</th>
                <th className="px-4 py-3 text-left text-xs font-medium uppercase tracking-widest text-gray-400">Actions</th>
              </tr>
            </thead>
            <tbody>
              {(reports ?? []).slice(0, 14).map((r: DailyReport) => (
                <tr key={r.report_date} className="border-b border-gray-100 hover:bg-gray-50 transition-colors">
                  <td className="px-4 py-3 font-mono text-gray-700">{r.report_date}</td>
                  <td className="px-4 py-3 font-mono text-gray-700">{r.leads_discovered ?? 0}</td>
                  <td className="px-4 py-3 font-mono text-gray-700">{r.leads_qualified ?? 0}</td>
                  <td className="px-4 py-3 font-mono text-gray-700">{r.emails_sent ?? 0}</td>
                  <td className="px-4 py-3 font-mono text-gray-700">{r.emails_opened ?? 0}</td>
                  <td className="px-4 py-3">
                    <Button variant="ghost" size="sm" icon={<Download className="w-3.5 h-3.5" />} onClick={() => handleDownloadReport(r.report_date)}>
                      Download
                    </Button>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </Card>
    </div>
  );
}
