"""
PDF Proposal generator for Cold Scout OSS.
Simple black & white proposal using ReportLab.
"""
import os
from datetime import date
from typing import List, Optional
from reportlab.lib.pagesizes import A4
from reportlab.lib import colors
from reportlab.pdfgen import canvas
from loguru import logger

W, H = A4
PAD_X = 40
INNER = W - 2 * PAD_X


def generate_proposal_pdf(
    business_name: str,
    category: str,
    benefits: List[str],
    output_filename: str,
    rating: Optional[float] = None,
    review_count: Optional[int] = None,
    city: Optional[str] = None,
    qualification_notes: Optional[str] = None,
) -> str:
    os.makedirs("tmp", exist_ok=True)
    filepath = os.path.join("tmp", output_filename)

    c = canvas.Canvas(filepath, pagesize=A4)

    # Header
    c.setFillColor(colors.HexColor("#000000"))
    c.rect(0, H - 80, W, 80, fill=1, stroke=0)
    c.setFillColor(colors.white)
    c.setFont("Helvetica-Bold", 22)
    c.drawString(PAD_X, H - 50, "Cold Scout — Proposal")
    c.setFont("Helvetica", 11)
    c.drawString(PAD_X, H - 70, f"Prepared for: {business_name} | {date.today()}")

    # Business info
    y = H - 120
    c.setFillColor(colors.HexColor("#000000"))
    c.setFont("Helvetica-Bold", 14)
    c.drawString(PAD_X, y, f"Business: {business_name}")
    y -= 22
    c.setFont("Helvetica", 11)
    c.setFillColor(colors.HexColor("#333333"))
    if category:
        c.drawString(PAD_X, y, f"Category: {category}")
        y -= 18
    if city:
        c.drawString(PAD_X, y, f"Location: {city}")
        y -= 18
    if rating:
        c.drawString(PAD_X, y, f"Google Rating: {rating} ({review_count or 0} reviews)")
        y -= 18

    # Qualification notes
    if qualification_notes:
        y -= 10
        c.setFont("Helvetica-Bold", 12)
        c.setFillColor(colors.HexColor("#000000"))
        c.drawString(PAD_X, y, "Digital Assessment")
        y -= 18
        c.setFont("Helvetica", 10)
        c.setFillColor(colors.HexColor("#333333"))
        for note in qualification_notes.split(" | ")[:6]:
            if y < 100:
                break
            c.drawString(PAD_X + 10, y, f"- {note.strip()}")
            y -= 15

    # Benefits
    if benefits:
        y -= 20
        c.setFont("Helvetica-Bold", 12)
        c.setFillColor(colors.HexColor("#000000"))
        c.drawString(PAD_X, y, "Key Benefits")
        y -= 18
        c.setFont("Helvetica", 11)
        c.setFillColor(colors.HexColor("#333333"))
        for b in benefits[:5]:
            if y < 100:
                break
            c.drawString(PAD_X + 10, y, f"+ {b}")
            y -= 16

    # Footer
    c.setFillColor(colors.HexColor("#000000"))
    c.rect(0, 0, W, 40, fill=1, stroke=0)
    c.setFillColor(colors.white)
    c.setFont("Helvetica", 9)
    c.drawCentredString(W / 2, 15, "Generated by Cold Scout OSS")

    c.save()
    return filepath
